# Generated by Django 5.2.15 on 2026-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(choices=[('Highways', 'Highways'), ('Oil & Gas', 'Oil & Gas'), ('Railways', 'Railways'), ('Power Transmission', 'Power Transmission'), ('Solar', 'Solar'), ('Water Supply', 'Water Supply'), ('Mining', 'Mining'), ('Smart Cities', 'Smart Cities'), ('Metro Rail', 'Metro Rail'), ('Other', 'Other')], default='Highways', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('geojson', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
